apiVersion: v1
kind: Service
metadata:
  labels:
    app: ldap
  name: ldap-service
  namespace: openldap-sample
spec:
  ports:
    - name: host-ldap-ssl
      protocol: TCP
      port: 636
      targetPort: 636
      nodePort: 30636
    - name: host-ldap-tcp
      port: 389
      targetPort: 389
      nodePort: 30389
      protocol: TCP
  type: NodePort
  selector:
    app: ldap
