kind: ServiceAccount
apiVersion: v1
metadata:
  name: openldap
  namespace: openldap-sample
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:anyuid'
  namespace: openldap-sample
subjects:
  - kind: ServiceAccount
    name: openldap
    namespace: openldap-sample
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
